version: "3"
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      AWS_ENDPOINT_URL: http://localstack:4566
      HOST: 0.0.0.0
      PORT: 8080
      PYTHONUNBUFFERED: 1
    volumes:
      - ./src:/app/src
      - ~/.aws/credentials:/root/.aws/credentials
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_EXECUTOR: docker-reuse
      LAMBDA_REMOTE_DOCKER: 0
      LAMBDA_REMOVE_CONTAINERS: 1
      SERVICES: s3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
